---
- name: Create a test environment
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Retrieve all available Openstack images
      os_image_info:
      register: result
              
    - name: Show images
      debug:
        msg: "{{ result.openstack_image }}"