- os_router:
    cloud: mycloud
    state: present
    name: router4
    network: auto-network
    external_fixed_ips:
      - subnet: auto_subnet
        ip: 192.168.1.24
    interfaces:
      - private-subnet