---
- hosts: localhost
  tasks:
  - name: Création reseau12
    os_network:
      name: reseau12
  - name: Création reseau22
    os_network:
      name: reseau22
  - name: Création subnet1
  os_subnet:
    name: subnet1
    network_name: reseau12
    cidr: 192.168.1.0/24
     gateway_ip: 192.168.1.254
 - name: Création subnet2
   os_subnet:
     name: subnet2
     network_name: reseau22
     cidr: 192.168.2.0/24
     gateway_ip: 192.168.2.254
  - name: Création du routeur
    os_router:
      name: routeur1
      interfaces:
      - subnet1
      - subnet2
  - name: Création du serveur1
  os_server:
    name: server1
    auto_ip: no
    flavor: m1.tiny
    image: cirros
    network: reseau12
  - name: Création du serveur2
  os_server:
    name: server2
    auto_ip: no
    flavor: m1.tiny
    image: cirros
    network: reseau2
  - name: Autoriser le ping en sortie
  os_security_group_rule:
    security_group: default
    protocol: icmp
    remote_ip_prefix: 0.0.0.0/0
  - name: Autoriser le ping en entrée
  os_security_group_rule:
    security_group: default
    protocol: icmp
    direction: egress
    remote_ip_prefix: 0.0.0.0/0
    