---
- name: Create a test environment
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get Servers Info
      os_server_info:
        filters:
          vm_state: active
      register: result
    - debug:
        msg: "{{ result.openstack_servers }}"